# Generated by Django 3.2.5 on 2021-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifs',
            name='message',
            field=models.CharField(default='', max_length=150),
        ),
    ]
