# Generated by Django 3.2.5 on 2021-07-08 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzer',
            name='avatar',
            field=models.ImageField(default='foo.png', upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='uzer',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uzer',
            name='followers',
            field=models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uzer',
            name='following',
            field=models.ManyToManyField(related_name='follow_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uzer',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uzer',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uzer',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='uzer',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
