# Generated by Django 3.2.4 on 2021-07-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0010_alter_uzer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzer',
            name='avatar',
            field=models.ImageField(default='', upload_to='profile_pics/'),
        ),
    ]
